# ========================================
# 数据集配置

# ========================================
dataset:
  repo_id: omy_pnp_language  # 数据集仓库ID/名称，用于标识这个数据集
  root: ./demo_data_language  # 数据集的根目录路径，存放训练数据的文件夹

# ========================================
# 策略模型配置
# ========================================
policy:
  type: smolvla  # 策略类型：SmolVLM（小型视觉-语言-动作模型）
                 # 这是一个结合了视觉、语言理解和动作预测的多模态模型
  
  chunk_size: 5  # 动作块大小：每次预测5个连续的动作
                 # 例如：预测未来5步的机器人动作序列
  
  n_action_steps: 5  # 执行动作的步数：每次实际执行5步动作
                     # 与chunk_size配合使用，实现动作序列的平滑执行
  
  device: cuda  # 计算设备：使用GPU加速训练
                # 可选：cuda（GPU）或 cpu（CPU）

# ========================================
# 训练输出与保存配置
# ========================================
save_checkpoint: true  # 是否保存训练检查点（模型权重）
                       # true=保存，false=不保存

output_dir: ./ckpt/smolvla_omy  # 检查点保存目录
                                # 所有训练结果、模型权重都会保存在这里

# ========================================
# 训练超参数配置
# ========================================
batch_size: 32  # 批次大小：每次训练使用16个样本
                # 越大训练越快但需要更多显存
                # 16是常见的中等大小，适合大多数GPU

job_name: smolvla_omy  # 任务名称：用于标识这次训练任务
                       # 会在日志和wandb中显示

resume: false  # 是否从上次中断的地方继续训练
               # false=从头开始训练
               # true=从最后一个检查点继续

seed: 42  # 随机种子：控制训练过程的随机性
          # 使用相同的种子可以让实验结果可复现
          # 42是机器学习中常用的"幸运数字"

num_workers: 8  # 数据加载的并行工作进程数
                # 越多加载越快，但会占用更多CPU和内存
                # 通常设为CPU核心数的一半

# ========================================
# 训练步数与频率配置
# ========================================
steps: 500  # 总训练步数：训练20000步后停止
               # 20000步通常需要数小时到十几小时
               # 使用下划线只是为了方便阅读（20000也一样）

eval_freq: -1  # 评估频率：每隔多少步在验证集上评估一次
               # -1表示不进行评估（跳过验证）
               # 正数如1000表示每1000步评估一次

log_freq: 50  # 日志记录频率：每训练50步记录一次损失、学习率等信息
              # 用于监控训练过程，值越小日志越详细

save_freq: 10_000  # 检查点保存频率：每10000步保存一次模型
                   # 可以在训练中断后从这些检查点恢复
                   # 最终会保存在 ./ckpt/smolvla_omy/ 下

# ========================================
# 训练预设配置
# ========================================
use_policy_training_preset: true  # 使用策略训练的预设配置
                                  # true=自动加载优化器、学习率调度器等默认参数
                                  # 这些参数在LeRobot框架中已经调优过

# ========================================
# Weights & Biases 实验跟踪配置
# ========================================
wandb:
  enable: true  # 是否启用wandb进行实验跟踪和可视化
                # true=上传训练数据到wandb云端
                # false=不使用wandb（纯本地训练）
  
  project: smolvla_omy  # wandb项目名称
                        # 所有实验会归类到这个项目下
                        # 可以在 https://wandb.ai 查看
  
  #entity: 你的wandb用户名  # wandb账户名或团队名（已注释掉）
                           # 如果不填，会使用默认登录的账户
                           # ⚠️ 不要填API密钥！
  
  disable_artifact: true  # 禁用wandb的artifact功能
                         # artifact用于保存和版本化数据集/模型
                         # true=不上传大文件，节省空间和时间